### ISSUE TITLE
Node.js is not a programming language.

### ISSUE THREAD

**Issue by Miku-chan39** [chingh1123/chingh1123#2]
Node.js is not a programming language, it is a runtime.

**Comment by chingh1123** [comment]
awa

**Comment by chingh1123** [comment]
> Node.js is not a programming language, it is a runtime.

I just say language, didn't say programming language

**Comment by Miku-chan39** [comment]
it is not a language too

**Comment by Miku-chan39** [comment]
it is a runtime

**Comment by chingh1123** [comment]
lao

**Comment by Miku-chan39** [comment]
nou

**Comment by chingh1123** [comment]
okay, I will edit it.
so i will close this issue
